name: Python CI – api-findings-validator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
         pip install -r requirements.txt
         pip install pytest-html

      - name: Run pytest
        run: pytest -s --html=report.html --self-contained-html

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html
      - name: Notify Slack
        if: always()
        run: |
          STATUS="✅ Passed @Channel"
          if [ "${{ job.status }}" != "success" ]; then STATUS="❌ Failed"; fi
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"*API Findings Validator Tests*: ${STATUS}\nGitHub Actions run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}